# Generated by Django 4.1 on 2022-12-19 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[(1, "student"), (2, "teacher"), (3, "admin")],
                        max_length=7,
                        verbose_name="role",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Asignatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombreAsignatura",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="nombreAsignatura"
                    ),
                ),
            ],
            options={
                "ordering": ["nombreAsignatura"],
            },
        ),
        migrations.CreateModel(
            name="Cuestionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=100, verbose_name="titulo"),
                ),
                ("duracion", models.IntegerField(default=10, verbose_name="duracion")),
                (
                    "secuencial",
                    models.BooleanField(default=False, verbose_name="secuencial"),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="password"
                    ),
                ),
                ("fecha_visible", models.DateTimeField(verbose_name="fecha_visible")),
                ("fecha_apertura", models.DateTimeField(verbose_name="fecha_apertura")),
                ("fecha_cierre", models.DateTimeField(verbose_name="fecha_cierre")),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.asignatura"
                    ),
                ),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Intento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="nota"
                    ),
                ),
                (
                    "hash",
                    models.CharField(blank=True, max_length=254, verbose_name="hash"),
                ),
                (
                    "fecha_inicio",
                    models.DateTimeField(null=True, verbose_name="fecha_inicio"),
                ),
                (
                    "fecha_fin",
                    models.DateTimeField(null=True, verbose_name="fecha_fin"),
                ),
                (
                    "cuestionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cuestionario",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "cuestionario")},
            },
        ),
        migrations.CreateModel(
            name="OpcionTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_orden", models.PositiveSmallIntegerField()),
                (
                    "opcion",
                    models.CharField(blank=True, max_length=254, verbose_name="opcion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pregunta",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="pregunta"
                    ),
                ),
                (
                    "titulo",
                    models.CharField(blank=True, max_length=254, verbose_name="titulo"),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.asignatura"
                    ),
                ),
            ],
            options={
                "ordering": ["pregunta"],
                "unique_together": {("pregunta", "asignatura")},
            },
        ),
        migrations.CreateModel(
            name="PreguntaText",
            fields=[
                (
                    "pregunta_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.pregunta",
                    ),
                ),
                ("respuesta", models.TextField()),
            ],
            bases=("api.pregunta",),
        ),
        migrations.CreateModel(
            name="RespuestaEnviadaText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "respuesta",
                    models.CharField(
                        blank=True, max_length=254, verbose_name="respuesta"
                    ),
                ),
                (
                    "intento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.intento"
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pregunta"
                    ),
                ),
            ],
            options={
                "ordering": ["pregunta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RespuestaEnviadaTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "intento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.intento"
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pregunta"
                    ),
                ),
                (
                    "respuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.opciontest"
                    ),
                ),
            ],
            options={
                "ordering": ["pregunta"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PreguntaCuestionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nPregunta", models.IntegerField()),
                (
                    "puntosAcierto",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=30,
                        verbose_name="puntosAcierto",
                    ),
                ),
                (
                    "puntosFallo",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=30,
                        verbose_name="puntosFallo",
                    ),
                ),
                (
                    "cuestionario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.cuestionario",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="api.pregunta",
                    ),
                ),
            ],
            options={
                "ordering": ["pregunta"],
                "unique_together": {("pregunta", "cuestionario")},
            },
        ),
        migrations.AddField(
            model_name="cuestionario",
            name="preguntas",
            field=models.ManyToManyField(
                through="api.PreguntaCuestionario", to="api.pregunta"
            ),
        ),
        migrations.AddField(
            model_name="cuestionario",
            name="profesor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="PreguntaTest",
            fields=[
                (
                    "pregunta_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="api.pregunta",
                    ),
                ),
                (
                    "respuesta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.opciontest"
                    ),
                ),
            ],
            bases=("api.pregunta",),
        ),
        migrations.AddField(
            model_name="opciontest",
            name="pregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opciones_test",
                to="api.preguntatest",
            ),
        ),
        migrations.CreateModel(
            name="Imparte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.asignatura"
                    ),
                ),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("profesor", "asignatura")},
            },
        ),
        migrations.CreateModel(
            name="Cursa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asignatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.asignatura"
                    ),
                ),
            ],
            options={
                "unique_together": {("alumno", "asignatura")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="cuestionario",
            unique_together={("asignatura", "titulo")},
        ),
        migrations.AlterUniqueTogether(
            name="opciontest",
            unique_together={("pregunta", "opcion", "num_orden")},
        ),
    ]
