# Generated by Django 4.1 on 2022-12-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("teacher", "teacher"),
                    ("admin", "admin"),
                ],
                max_length=7,
                verbose_name="role",
            ),
        ),
    ]
