# Generated by Django 4.1 on 2023-02-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="preguntacuestionario",
            name="aleatorizar",
            field=models.BooleanField(default=False),
        ),
    ]
