# Generated by Django 4.1 on 2022-10-02 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perteneceacuestionario",
            name="idPregunta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="api.preguntas",
            ),
        ),
    ]
