# Generated by Django 4.1 on 2022-12-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="intento",
            name="hash_offline",
            field=models.CharField(
                blank=True, max_length=254, verbose_name="hash_offline"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="opciontest",
            unique_together={("pregunta", "opcion")},
        ),
        migrations.RemoveField(
            model_name="opciontest",
            name="num_orden",
        ),
    ]
