# Generated by Django 4.1 on 2022-12-20 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_intento_hash_offline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preguntatest",
            name="respuesta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.opciontest",
            ),
        ),
    ]
